[package]
name = "tobacco_service_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.8.0", package = "libadwaita", features = ["v1_5"] }
anyhow = "1.0.98"
gtk4 = "0.10.0"
zbus = "5.9.0"
