[package]
name = "tobacco_service_manager"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.8.0", package = "libadwaita", features = ["v1_5"] }
gtk4 = "0.10.0"
rayon = "1.10.0"
users = "0.11.0"
zbus = "5.9.0"
